### PR TITLE
feat: allow ToS and Privacy Policy to be edited

### LINKED ISSUE #1445: Add privacy policy and terms of service

### PR DESCRIPTION
**Pull request by jobara**
- Migrates ToS and Privacy Policy to be editable in a Filament admin form.
- Restores prefixes to route groups that were removed in #1926 

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Review by greatislander — COMMENTED** [review]
It would be helpful to add a "Pages" link to the admin dashboard quick links sidebar. My approach was to make that sidebar match the sidebar in filament:

Screenshot 2023-11-03 at 9 08 45 AM

**Review by greatislander — CHANGES_REQUESTED** [review]
I think it would be very helpful to provide a link to view the published page in the table view and in the edit view.

**Review by greatislander — CHANGES_REQUESTED** [review]
The Markdown editor has significant contrast issues in dark mode:

Screenshot 2023-11-03 at 9 12 40 AM

**Review by greatislander — CHANGES_REQUESTED** [review]
Code coverage should be increased for the new Filament pages. This is fairly straightforward, see: https://github.com/accessibility-exchange/platform/blob/b72d4ba55914f874372b4dec80a4f3478e042006/tests/Feature/ResourceCollectionTest.php#L101-L132

**Comment by jobara** [comment]
> It would be helpful to add a "Pages" link to the admin dashboard quick links sidebar. My approach was to make that sidebar match the sidebar in filament:
> 
> Screenshot 2023-11-03 at 9 08 45 AM

Sorry, I forgot to note why I didn't do this. Basically I intentionally left it out because it will break/invalidate the ASL/LSQ interpretation videos for the quick links. Perhaps we should put it in anyways, but that's why I left it out.

**Comment by greatislander** [comment]
> > It would be helpful to add a "Pages" link to the admin dashboard quick links sidebar. My approach was to make that sidebar match the sidebar in filament:
> > Screenshot 2023-11-03 at 9 08 45 AM
> 
> Sorry, I forgot to note why I didn't do this. Basically I intentionally left it out because it will break/invalidate the ASL/LSQ interpretation videos for the quick links. Perhaps we should put it in anyways, but that's why I left it out.

I didn't realize there were ASL videos for the admin-facing pages too. Okay.

**Comment by jobara** [comment]
> The Markdown editor has significant contrast issues in dark mode:
> 
> Screenshot 2023-11-03 at 9 12 40 AM

I filed an issue with Filament. https://github.com/filamentphp/filament/issues/9497

**Comment by jobara** [comment]
> > > It would be helpful to add a "Pages" link to the admin dashboard quick links sidebar. My approach was to make that sidebar match the sidebar in filament:
> > > Screenshot 2023-11-03 at 9 08 45 AM
> > 
> > 
> > Sorry, I forgot to note why I didn't do this. Basically I intentionally left it out because it will break/invalidate the ASL/LSQ interpretation videos for the quick links. Perhaps we should put it in anyways, but that's why I left it out.
> 
> I didn't realize there were ASL videos for the admin-facing pages too. Okay.

Quite a bit of the content was pulled for ASL/LSQ interpretation and should be up on the [dev site](https://dev.accessibilityexchange.ca/) now. Even some things I hadn't anticipated like notifications and alerts. I've made the change to this part for now though and will come in my next push. I'm still debating though, and it might get pulled out again, but it is something that will need to be updated at some point.

**Comment by jobara** [comment]
> > The Markdown editor has significant contrast issues in dark mode:
> > Screenshot 2023-11-03 at 9 12 40 AM
> 
> I filed an issue with Filament. [filamentphp/filament#9497](https://github.com/filamentphp/filament/issues/9497)

@greatislander this probably won't be addressed before our F&F release. I've filed a new issue to track it. See: #1965

**Review by greatislander — APPROVED** [review]

**Pull request merged**
