### PR TITLE
feat: populate CHHA course (resolves #1630, #1641, #1642, #1643, #1644)

### LINKED ISSUE #1630: Populate the CHHA course
We should now have all of the content for the CHHA course from Logan. We should replace the 'sample course' with this content.

### LINKED ISSUE #1641: Training module: Fake breadcrumb
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I go to the page for a specific module, I see the breadcrumb "back>sample course". This whole thing is a link back to the course page. The formatting is not true to an actual breadcrumb, as it uses ">" and the whole thing is a link. I prefer the latter as it's more consistent with the breadcrumbs used in other parts of the site.

**Expected behavior**
Either have "<back" with < being a left chevron as the link, or have "Resources > Sample course", with > being a right chevron and only "Sample course" as the link to the course page, and "Resources" back to the resource page.

### LINKED ISSUE #1642: Course page: Use breadcrumb instead of "back"
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
On the course page, there is a "back" link under the H1. The language and the placement is inconsistent with the rest of the site.

**Expected behavior**
Have the breadcrumb read "Resources > Sample Course" with > being a right chevron and "Resources" linking back to the resources page.

### LINKED ISSUE #1643: Training module quiz: No page level error
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I don't answer some questions on the quiz, and it produces an error, it only appears inline but not at the top of the page. This makes it easy to miss.

**Expected behavior**
Please have a page level error that says "Some questions have not been answered."

### LINKED ISSUE #1644: Training module quiz: Results page - "back to training home page" ambiguous
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
On the results page after successfully completing the quiz, there's a button that says "Back to training home page". I wasn't sure where that led.

**To Reproduce**
1. Go to a training module
2. Watch all the videos and answer all the quiz questions correctly
3. See the button

**Expected behavior**
Ideally the button would say "Back to [name of training]".
Screenshot 2023-04-03 at 5 00 47 PM

### PR DESCRIPTION
**Pull request by jobara**
Resolves #1630 
Resolves #1641 
Resolves #1642 
Resolves #1643
Resolves #1644 

- Populates the CHHA course
- Puts quiz questions into an ordered list
- Adds placeholders for sign language videos into the quiz for each question and set of choices.
- Adds breadcrumbs to course landing page
- Improves breadcrumbs for course modules
- Updates back button for quiz
- Fixes slug database column type for course and module
- Makes course author a translatable field
- Adds the page level error validation message

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Review by greatislander — COMMENTED** [review]
A few notes:

1. I notice the User/Module relationship has an (unused?) `completed_at` field. It looks like the user's module progress is saved in `started_content_at` and `finished_content_at`. Should `completed_at` be dropped from the pivot table?
2. The `completed` badges look a little weird — the vertical positioning doesn't seem consistent (compare left and right module cards) and in at least one case, they could use a little more padding on the left:

Screenshot 2023-07-18 at 2 58 21 PM

3. For quiz questions with "all of the above" part of me thinks that checking "all of the above" should uncheck the other questions and disable the checkboxes. Right now if you check all of them and then check all of the above the answer is wrong.
4. I got the email after I finished the quiz. The references to "Certificate" are a bit confusing because it doesn't include a certificate or anything, it's just text confirming completion. I wonder if the language should be changed to say that once you complete the course content and the quiz, you will receive email confirmation of course completion or something along those lines. I know the videos say certificate which is unfortunate.

**Comment by chosww** [comment]
I found the completion of modules a bit weird with actual content; when we were implementing the logic for completion of a module, I thought it makes sense to mark it as completed once the module is fully watched, but I am not sure if users would understand that logic without any hints. The modules have irrelevant information to the course at the end, as well as a little term before the video player is fully finished. I imagine some users would just press go back few seconds before the full completion and wonder why the course is still marked as in-progress. Could we give some hint on the page saying that a module is completed once the video is fully watched?

**Comment by jobara** [comment]
@cherylhjli do you have thoughts about the above comments by @greatislander and @chosww? I might be able to address some of the these issues in this PR, but some might need to be moved to their own issues.

**Comment by jobara** [comment]
> 2. The `completed` badges look a little weird — the vertical positioning doesn't seem consistent (compare left and right module cards) and in at least one case, they could use a little more padding on the left:
> 
> Screenshot 2023-07-18 at 2 58 21 PM

The above was addressed in https://github.com/accessibility-exchange/platform/pull/1851/commits/9f7e39c1f700458551ade42afcc8f333f567f38a

**Comment by jobara** [comment]
> 1. I notice the User/Module relationship has an (unused?) `completed_at` field. It looks like the user's module progress is saved in `started_content_at` and `finished_content_at`. Should `completed_at` be dropped from the pivot table?

Removed `completed_at` at https://github.com/accessibility-exchange/platform/pull/1851/commits/61a16507aa6837f6dd9487d72946a3663a6e27fc

**Comment by jobara** [comment]
> 3. For quiz questions with "all of the above" part of me thinks that checking "all of the above" should uncheck the other questions and disable the checkboxes. Right now if you check all of them and then check all of the above the answer is wrong.

Filed as https://github.com/accessibility-exchange/platform/issues/1857

**Comment by jobara** [comment]
> I found the completion of modules a bit weird with actual content; when we were implementing the logic for completion of a module, I thought it makes sense to mark it as completed once the module is fully watched, but I am not sure if users would understand that logic without any hints. The modules have irrelevant information to the course at the end, as well as a little term before the video player is fully finished. I imagine some users would just press go back few seconds before the full completion and wonder why the course is still marked as in-progress. Could we give some hint on the page saying that a module is completed once the video is fully watched?

Filed as https://github.com/accessibility-exchange/platform/issues/1856

**Comment by jobara** [comment]
> 4. I got the email after I finished the quiz. The references to "Certificate" are a bit confusing because it doesn't include a certificate or anything, it's just text confirming completion. I wonder if the language should be changed to say that once you complete the course content and the quiz, you will receive email confirmation of course completion or something along those lines. I know the videos say certificate which is unfortunate.

@cherylhjli Do you think we can just change `certificate` to `confirmation`? One thing to also consider is that the language change will affect translations and the signed interoperation videos.

**Comment by cherylhjli** [comment]
> 

Has this been sent to translation yet? If it has I'm tempted to leave it as it is.

**Comment by jobara** [comment]
> Has this been sent to translation yet? If it has I'm tempted to leave it as it is.

At least one instance has, and that has also been sent for sign language interpretation.

**Comment by jobara** [comment]
> 4\. I got the email after I finished the quiz. The references to "Certificate" are a bit confusing because it doesn't include a certificate or anything, it's just text confirming completion. I wonder if the language should be changed to say that once you complete the course content and the quiz, you will receive email confirmation of course completion or something along those lines. I know the videos say certificate which is unfortunate.

@greatislander and @cherylhjli I've filed this as #1859 so we can consider it for a future change.

**Comment by jobara** [comment]
@greatislander ready for another round of review.

**Review by greatislander — APPROVED** [review]
It looks like all the issue I identified have been addressed or filed as separate tickets for later follow-up.

**Pull request merged**
