### PR TITLE
feat: add page to manage basic website settings

### PR DESCRIPTION
**Pull request by greatislander**
A while back I set up the Spatie [valuestore](https://github.com/spatie/valuestore) package to store some basic website settings such as contact email, phone, and mailing address. I've added a drop-in Filament plugin to make these editable by administrators.

I also realized there were a few instances of the old `@markdown` directive still in use, so I replaced them with Laravel's built-in `Str::markdown` helper and removed the package.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander the existing values for the website settings are not populated into the admin panel.

empty settings

**Comment by greatislander** [comment]
@jobara Correct— those are set as fallbacks in the `settings()` helper. So once the updates are deployed they will need to be added.

For some reason the `default()` helper isn't working— not entirely sure why.

**Comment by jobara** [comment]
> For some reason the `default()` helper isn't working— not entirely sure why.

From the Filament docs for [default()](https://filamentphp.com/docs/2.x/forms/fields#setting-a-default-value), it says:

> Note that inside the admin panel this only works on Create Pages, as Edit Pages will always fill the data from the model.

I'm not sure if this is the exact problem here, but it might be. If it is the case,  we may need to seed the model from he settings?

Also, have you considered the [spatie-laravel-settings-plugin](https://filamentphp.com/docs/2.x/spatie-laravel-settings-plugin/getting-started)? Would it be applicable to our use case and work better?

**Comment by greatislander** [comment]
To populate the default content, we need to add this JSON blob to `/storage/app/settings.json` on the dev, staging, and production sites.

```json
{"phone":"+1-888-867-0053","email":"test@accessibilityexchange.ca","address":"The Accessibility Exchange \u2105 IRIS  \n1 University Avenue, 3rd Floor  \nToronto, ON M5J 2P1","facebook":"https:\/\/facebook.com\/AccessXchange","linkedin":"https:\/\/linkedin.com\/company\/the-accessibility-exchange\/","twitter":"https:\/\/twitter.com\/AccessXchange","youtube":"https:\/\/www.youtube.com\/channel\/UC-mIk4Xk04wF4urFSKZQOAA"}
```

**Review by jobara — APPROVED** [review]

**Pull request merged**
