### PR TITLE
feat: upgrade Filament and Livewire to 3.x (resolves #1927)

### LINKED ISSUE #1927: Upgrade Filament and Livewire to 3.x
**Is your feature request related to a problem? Please describe.**

See:

- [ ] https://livewire.laravel.com/docs/upgrading
- [ ] https://filamentphp.com/docs/3.x/panels/upgrade-guide
- [ ] https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

**Describe the solution you'd like**

Upgrade Filament and Livewire to 3.x.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Not applicable.

### PR DESCRIPTION
**Pull request by greatislander**
Upgrades Filament and Livewire to 3.x.

You'll need to run `composer install` and `npm install` and likely `php artisan view:clear` to test this properly.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by chosww** [comment]
Create/update resources in the authoring interface seems to have issues to display localized value for Content type, Topics, Sectors, and Areas of impact.

**Comment by chosww** [comment]
The application crashes when I change number of items to display per pagination to "All" in interpretation section of the authoring interface. 

Steps to reproduce:

1. Go to the admin page
2. Go to Sign language interpretation tab
3. At the bottom where it shows number of results per pagination, change the option to "All"
4. Observe the application crash

Note: this happened when there were a few hundred interpretation videos -- with less interpretation videos, I can't reproduce the error.

**Comment by greatislander** [comment]
@chosww I have changed the pagination so that you can view max 50 items per page. I think that is a safe ceiling and seems to perform well on my end.

**Comment by jobara** [comment]
@greatislander would you be able to review the contrast for the "badge" like things in the tables. For example the one that shows the categories for the Identities seems really low. Although I think others may also be too low too. 

Screenshot of the identities table

Screenshot of the age group cluster contrast ratio

**Comment by jobara** [comment]
@greatislander when attaching a resource to a collection the drop down shows the JSON text instead of the name. I think you've fixed this elsewhere before.

Screenshot of JSON in the dropdown

**Comment by chosww** [comment]
When I create an interpretation with undefined route name, I see the application crashes on the authoring interface's interpretation section. 

Steps to reproduce:

1. Sign in as an admin account
2. Go to the authoring interface's interpretations tab
3. Create a new interpretation, I used name "name" and route "route"
4. See the application crashes after pressing create button

Error message:

Symfony\Component\ Routing\ Exception\ RouteNotFoundException PHP 8.1.9 10.28.0
Route [en.route] not defined.

Where the error occurred:
app/ Filament/Resources/InterpretationResource.php: 59

**Comment by jobara** [comment]
@greatislander I tried updating the website settings and ran into the following error.

`SQLSTATE[HY000]: General error: 1364 Field 'locked' doesn't have a default value `

```error
insert into `settings` (`created_at`, `group`, `name`, `payload`, `updated_at`) values (2023-10-16 14:41:42, general, email, "support@accessibilityexchange.ca", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, phone, "+1-888-867-0053", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, address, "The Accessibility Exchange \u2105 IRIS - Test\n20-850 King Street West\nOshawa, ON, L1J 8N5", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, facebook, "https:\/\/facebook.com\/AccessXchange", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, linkedin, "https:\/\/linkedin.com\/company\/the-accessibility-exchange\/", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, twitter, "https:\/\/twitter.com\/AccessXchange", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, youtube, "https:\/\/www.youtube.com\/channel\/UC-mIk4Xk04wF4urFSKZQOAA", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, individual_orientation, "https:\/\/share.hsforms.com\/161eyaBsQS-iv1z0TZLwdQwdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, org_orientation, "https:\/\/share.hsforms.com\/1sB6UV4gvQlC_0QxQ3q3z1Adfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, fro_orientation, "https:\/\/share.hsforms.com\/1gGf9TjhaQ0uaqcnyJfSDlwdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, ac_application, "https:\/\/share.hsforms.com\/16bxWtxLKQmCdjZo4TmJU9wdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, cc_application, "https:\/\/share.hsforms.com\/1Pkmwsp2RT9mrvFh2d9iYfQdfpez", 2023-10-16 14:41:42) on duplicate key update `payload` = values(`payload`), `updated_at` = values(`updated_at`)
```

**Comment by chosww** [comment]
Screen Shot 2023-10-16 at 10 52 44 AM

The filter drop down of the resources section shows JSON text for "Content types".

**Comment by greatislander** [comment]
> When I create an interpretation with undefined route name, I see the application crashes on the authoring interface's interpretation section.
> 
> Steps to reproduce:
> 
> 1. Sign in as an admin account
> 2. Go to the authoring interface's interpretations tab
> 3. Create a new interpretation, I used name "name" and route "route"
> 4. See the application crashes after pressing create button
> 
> Error message:
> 
> Symfony\Component\ Routing\ Exception\ RouteNotFoundException PHP 8.1.9 10.28.0 Route [en.route] not defined.
> 
> Where the error occurred: app/ Filament/Resources/InterpretationResource.php: 59

This is not a new issue. The table provides a link to the route using `localized_route` so if you give it a nonexistent route it will cause an error.

**Comment by chosww** [comment]
> > When I create an interpretation with undefined route name, I see the application crashes on the authoring interface's interpretation section.
> > Steps to reproduce:
> > 
> > 1. Sign in as an admin account
> > 2. Go to the authoring interface's interpretations tab
> > 3. Create a new interpretation, I used name "name" and route "route"
> > 4. See the application crashes after pressing create button
> > 
> > Error message:
> > Symfony\Component\ Routing\ Exception\ RouteNotFoundException PHP 8.1.9 10.28.0 Route [en.route] not defined.
> > Where the error occurred: app/ Filament/Resources/InterpretationResource.php: 59
> 
> This is not a new issue. The table provides a link to the route using `localized_route` so if you give it a nonexistent route it will cause an error.

I think we need to check if the route exist before performing anything. Once an interpretation with undefined route is created using the authoring interface, the interpretation tab becomes unusable -- the error pops up again, as soon as I navigate to the tab.

**Comment by greatislander** [comment]
> > > When I create an interpretation with undefined route name, I see the application crashes on the authoring interface's interpretation section.
> > > Steps to reproduce:
> > > 
> > > 1. Sign in as an admin account
> > > 2. Go to the authoring interface's interpretations tab
> > > 3. Create a new interpretation, I used name "name" and route "route"
> > > 4. See the application crashes after pressing create button
> > > 
> > > Error message:
> > > Symfony\Component\ Routing\ Exception\ RouteNotFoundException PHP 8.1.9 10.28.0 Route [en.route] not defined.
> > > Where the error occurred: app/ Filament/Resources/InterpretationResource.php: 59
> > 
> > 
> > This is not a new issue. The table provides a link to the route using `localized_route` so if you give it a nonexistent route it will cause an error.
> 
> I think we need to check if the route exist before performing anything. Once an interpretation with undefined route is created using the authoring interface, the interpretation tab becomes unusable -- the error pops up again, as soon as I navigate to the tab.

@chosww Can you file a new issue for that?

**Comment by greatislander** [comment]
> @greatislander I tried updating the website settings and ran into the following error.
> 
> `SQLSTATE[HY000]: General error: 1364 Field 'locked' doesn't have a default value `
> 
> ```
> insert into `settings` (`created_at`, `group`, `name`, `payload`, `updated_at`) values (2023-10-16 14:41:42, general, email, "support@accessibilityexchange.ca", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, phone, "+1-888-867-0053", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, address, "The Accessibility Exchange \u2105 IRIS - Test\n20-850 King Street West\nOshawa, ON, L1J 8N5", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, facebook, "https:\/\/facebook.com\/AccessXchange", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, linkedin, "https:\/\/linkedin.com\/company\/the-accessibility-exchange\/", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, twitter, "https:\/\/twitter.com\/AccessXchange", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, youtube, "https:\/\/www.youtube.com\/channel\/UC-mIk4Xk04wF4urFSKZQOAA", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, individual_orientation, "https:\/\/share.hsforms.com\/161eyaBsQS-iv1z0TZLwdQwdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, org_orientation, "https:\/\/share.hsforms.com\/1sB6UV4gvQlC_0QxQ3q3z1Adfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, fro_orientation, "https:\/\/share.hsforms.com\/1gGf9TjhaQ0uaqcnyJfSDlwdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, ac_application, "https:\/\/share.hsforms.com\/16bxWtxLKQmCdjZo4TmJU9wdfpez", 2023-10-16 14:41:42), (2023-10-16 14:41:42, general, cc_application, "https:\/\/share.hsforms.com\/1Pkmwsp2RT9mrvFh2d9iYfQdfpez", 2023-10-16 14:41:42) on duplicate key update `payload` = values(`payload`), `updated_at` = values(`updated_at`)
> ```

Found the issue: https://github.com/spatie/laravel-settings/pull/218

**Comment by greatislander** [comment]
@jobara should be ready for final review once tests pass.

**Comment by jobara** [comment]
@greatislander the yes and no badges are below contrast requirements.

Yes/No badges low contrast in light mode
Screenshot showing contrast ratio for yes badge in light mode
Screenshot showing contrast ratio for no badge in light mode
Screenshot showing contrast ratio for yes badge in dark mode
Screenshot showing contrast ratio for no badge in dark mode

**Comment by jobara** [comment]
> @greatislander the yes and no badges are below contrast requirements.
> 
> Yes/No badges low contrast in light mode Screenshot showing contrast ratio for yes badge in light mode Screenshot showing contrast ratio for no badge in light mode Screenshot showing contrast ratio for yes badge in dark mode Screenshot showing contrast ratio for no badge in dark mode

While there was an issue with one of the badges, it turns out the larger issue is related to the fact that the text had been selected and was factoring into the contrast ratio calculation. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1859540

**Review by jobara — APPROVED** [review]

**Pull request merged**
