### PR TITLE
feat: admin panel for training modules (resolves #395, #397)

### LINKED ISSUE #395: Training modules: edit

### LINKED ISSUE #397: Training modules: quiz editing

### PR DESCRIPTION
**Pull request by jobara**
Resolves #395 
Resolves #397

Adds the admin interface adding training modules including adding courses, modules, questions, quizzes. 

Blocked by: requires changes from #1390

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [ ] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by greatislander** [comment]
@jobara I think this is a blocker for https://github.com/accessibility-exchange/platform/issues/1906

**Comment by jobara** [comment]
> @jobara I think this is a blocker for #1906

Do you see this as a blocker because it will be hard to reconcile this PR after the update? If that's the case I think we'll need to redo much of this work anyways, as there were already a bunch of changes to the course related models that this PR was basing things off of. So it might be better to just mothball this and keep it as a reference until we've actually implemented the admin interface for the training modules. 

Let me know what you think.

**Comment by greatislander** [comment]
> > @jobara I think this is a blocker for #1906
> 
> Do you see this as a blocker because it will be hard to reconcile this PR after the update? If that's the case I think we'll need to redo much of this work anyways, as there were already a bunch of changes to the course related models that this PR was basing things off of. So it might be better to just mothball this and keep it as a reference until we've actually implemented the admin interface for the training modules.
> 
> Let me know what you think.

Given that context I think yes, you should probably mothball this.

**Comment by jobara** [comment]
Closing for now to reduce clutter in the PR tab. Can search for this via the mothballed label later if needed.

**Pull request closed without merging**
