### PR TITLE
fix: robots and sitemap served at /storage path (resolves #1998)

### LINKED ISSUE #1998: On the deployed sites robots.txt and sitemap.xml are served under the /storage path
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

It is expected that the robots.txt and sitemap.xml are served from the root of the site like `https://accessibilityexchange.ca/robots.txt`; however they are accessibly only through the `storage` path like `https://accessibilityexchange.ca/storage/robots.txt`.

**To Reproduce**
1. Go to <https://accessibilityexchange.ca/robots.txt>
2. Notice the 404 error
3. Go to <https://accessibilityexchange.ca/storage/robots.txt>
4. See the contents of the robots.txt file

**Expected behavior**

The robots and sitemap files should be served from the root of the site.

### PR DESCRIPTION
**Pull request by jobara**
Resolves #1998 

- Adds symlinks for the sitemap and robots files into the public directory
- Updates/cleans up tests

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [ ] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Review by chosww — APPROVED** [review]

**Review by greatislander — CHANGES_REQUESTED** [review]
I commented on the issue by mistake:

https://github.com/accessibility-exchange/platform/issues/1998#issuecomment-1822946774
https://github.com/accessibility-exchange/platform/issues/1998#issuecomment-1822947524

**Comment by jobara** [comment]
> I commented on the issue by mistake:
> 
> [#1998 (comment)](https://github.com/accessibility-exchange/platform/issues/1998#issuecomment-1822946774) [#1998 (comment)](https://github.com/accessibility-exchange/platform/issues/1998#issuecomment-1822947524)

Regarding the links, they are being run in the deployed environment and I ran them locally. I also went into the deploy server and tried to run them again, but it said it was already done. 

Are you thinking of adding a symlink from storage into the public path? I guess we could try that too, although the files would be accessible at /robots.txt and /storage/robots.txt although I guess that isn't a huge issue.

**Review by greatislander — CHANGES_REQUESTED** [review]
We can add additional links in `config/filesystems.php`:

```php
        public_path('sitemap.xml') => storage_path('app/public/sitemap.xml'),
        public_path('robots.txt') => storage_path('app/public/robots.txt'),
```

**Review by greatislander — APPROVED** [review]

**Comment by chosww** [comment]
Thanks @jobara, using links as @greatislander suggested looks great 👍

**Pull request merged**
