### PR TITLE
fix: resolve issues with creating/editing selection criteria

### PR DESCRIPTION
**Pull request by greatislander**
Resolves issues identified in https://github.com/accessibility-exchange/platform/pull/901#issuecomment-1234426885.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and committed built assets to the PR branch.

### CODE REVIEW

**Review by chosww — APPROVED** [review]
Thanks for the awesome work @greatislander! Two things I noticed:

1. Intersectional section radio button is set to "Yes" by default, when other sections are set to "No" by default.
2. Error message for disability and identity types could be customized; currently the error messages say: "The disability types field is required when cross disability is 0." and "The other identity type field is required when intersectional is 0."

But other than that all the issues @cherylhjli has spotted are fixed and code changes look good.

**Comment by greatislander** [comment]
> Thanks for the awesome work @greatislander! Two things I noticed:
> 
> 1. Intersectional section radio button is set to "Yes" by default, when other sections are set to "No" by default.
> 2. Error message for disability and identity types could be customized; currently the error messages say: "The disability types field is required when cross disability is 0." and "The other identity type field is required when intersectional is 0."
> 
> But other than that all the issues @cherylhjli has spotted are fixed and code changes look good.

Those are both expected, @chosww. Thank you for noting them! @cherylhjli Can you review these error messages and add them to your spreadsheet?

**Comment by cherylhjli** [comment]
With this issue:

> If there is an error with any other field on the page, the location goes back to specific provinces and territories even if I entered specific cities and towns. If I select cities and towns radio button, it does load up any locations I’ve previously inputted. Desired behaviour is for the specific cities and towns radio button to remain selected, and to show any entered cities and towns below.

When I save and the page refreshes, the "location" is still "all provinces and territories" despite specific cities and towns selected. However when I open up the "edit location criteria" dropdown, I can see that the specific cities or towns radio button is selected.
Screen Shot 2022-09-06 at 4 42 00 PM

Also, "Other identitities" still has "intersectional" below even when a specific intersection has been selected:
Screen Shot 2022-09-06 at 4 46 45 PM
Desired behaviour: Show the selected type of experiences or identities, as well as the specific selection within that

With this issue:

> If I pick “age” and specify specific age brackets, but I don’t fill in the minimum and ideal participants and I save it and it produces an error, I come back and it didn’t save my age selection. I haven’t tested this with the other identities/experiences but it might be the same behaviour

I'm noticing that it comes up for gender and sexual identity as well.

**Comment by greatislander** [comment]
Remaining issues:

- gender/sexuality doesn't persist if other fields have errors
- summaries may not be accurate once fields have been edited; when the form is submitted, if there are errors the summaries should be hidden and the edit areas should be expanded

**Pull request merged**
