### PR TITLE
feat: adds a dark mode to the admin theme

### PR DESCRIPTION
**Pull request by greatislander**
Follow-up to #1407. NOTE: does not respect user preferences from front-end. Admin swill have to set their dark mode preference independently.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander how can I test the locale switching for the logo and the dark mode?

**Comment by greatislander** [comment]
@jobara you can't :( I just figured I'd build it properly so if admin locales are implemented it will pick up the appropriate locale.

**Comment by jobara** [comment]
Does the [`dark mode`](https://filamentphp.com/docs/2.x/admin/appearance#dark-mode) config setting need to be re-enabled?

**Comment by greatislander** [comment]
> Does the [`dark mode`](https://filamentphp.com/docs/2.x/admin/appearance#dark-mode) config setting need to be re-enabled?

Weird, I thought I had done that— fixed in 187f8df.

**Review by jobara — APPROVED** [review]

**Pull request merged**
