### PR TITLE
feat: replace LiveWire datepicker with Alpine Date Input component

### LINKED ISSUE #1063: number inputs for date selection lag when using the mouse
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

Using the mouse to quickly interact with the up/down arrows on the number input spinner results in the input going back and forth and potentially landing on the wrong date.

**To Reproduce**
1. Go to project creation page
2. Set the project time frame
3. Quickly click on the up/down arrows for the year or day fields
4. Notice the numbers not incrementing/decrementing smoothly. It will work properly using the keyboard, which can be used as a comparison.

**Expected behavior**

The numbers increment and decrement smoothly in the correct direction and result in the correct value being input.

**Screenshots**

The project timeframe inputs

**Details**
- Device: MBP
- Operating system: macOS 12.6
- Browser: Firefox 104.0.2
- Link to affected page: 

**Additional context**

Seems to work in Chrome.

### LINKED ISSUE #1296: Date input doesn't properly persist value if it doesn't lose focus before form is submitted
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
If a date input is the last field on the page, and it still has focus when the form is submitted using a pointing device (mouse or trackpad), the input value will not be properly submitted with the form request.

**Expected behavior**
All data entered should be submitted.

**Screenshots**
Not applicable.

### PR DESCRIPTION
**Pull request by greatislander**
Resolves #1063.
Resolves #1296.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by chosww** [comment]
Pressing enter key on the date picker submits the working form.

**Comment by chosww** [comment]
Submitting 0 to the year result in 1900, and any number with 2 digits get appended to 19**, so submitting 99 would result in 1999. Once 3 digits entered, it seems like to shift the year by 3, so entering 3 digit numbers like 300 becomes 190(0300) -- the number in the brackets.

**Comment by chosww** [comment]
Entering 6+ digits in day column results in SQL error "Invalid datetime format: 1292 Incorrect date value: '0300-10-100000' for column 'signup_by_date' at row 1".

**Comment by greatislander** [comment]
> Pressing enter key on the date picker submits the working form.

Is this new behaviour? I think that's expected if you are in a text input. On the expanded month select it should make a choice within the select.

**Comment by chosww** [comment]
> > Pressing enter key on the date picker submits the working form.
> 
> Is this new behaviour? I think that's expected if you are in a text input. On the expanded month select it should make a choice within the select.

When there are multiple fields in a form with the date picker, submitting form by pressing enter on the date picker seems not right to me, as other input fields don't submit the form on enter.

**Comment by greatislander** [comment]
@chosww I've made the changes we discussed. Ready for another look.

**Comment by chosww** [comment]
> @chosww I've made the changes we discussed. Ready for another look.

The changes are working as expected.

**Review by chosww — APPROVED** [review]

**Pull request merged**
