### PR TITLE
fix: remove misleading copy about multiple accounts

### LINKED ISSUE #1156: Copy changes suggested by IRIS
Please view IRIS copy suggestion for the hard launch in the attached document:

[5 Oct - Copy inserts.docx](https://github.com/accessibility-exchange/platform/files/9759343/5.Oct.-.Copy.inserts.docx)

### PR DESCRIPTION
**Pull request by chosww**
Resolves issue #1156.

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [ ] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Review by greatislander — CHANGES_REQUESTED** [review]
@chosww Please run `composer localize` to remove the string from `resources/lang/en.json`

**Comment by greatislander** [comment]
@cherylhjli This removes the message completely. Is that what you wanted?

**Comment by cherylhjli** [comment]
@greatislander can we change it back to our original copy (with a small tweak)? "If more than one of these apply to you, you have the option to register additional accounts separately."

**Comment by greatislander** [comment]
@chosww Can you make this change?

**Review by greatislander — APPROVED** [review]

**Pull request merged**
