### PR TITLE
feat: manage estimates and agreements (resolves #1069)

### LINKED ISSUE #361: Design system / pagination links

### LINKED ISSUE #1069: Projects: handle estimates and agreements
**Is your feature request related to a problem? Please describe.**

Project organizations can:

- [ ] Request an estimate
- [ ] Mark an estimate as approved

Platform administrators can:

- [ ] Mark an estimate as returned
- [ ] Mark a signed agreement as received

**Describe the solution you'd like**

See above.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Not applicable.

### LINKED ISSUE #1074: Change any italic body text to non-italics
Pages italics appear on:

- [x] Individual: Creating page, step 2: Groups you can connect to: "As a Community Connector, a Regulated Organization may request your services to assist them in connecting to these groups."
- [x] Community Org: Creating page, step 2: Groups you can connect to: "Primary constituency means a group that’s specifically in your mandate to represent. As you’ve indicated that your organization is playing the role of Community Connector, a Regulated Organization may request your services to assist them in connecting to these groups. As you’ve indicated that your organization is playing the role of Consultation Participant, a Regulated Organization may ask you to represent this group’s point of view in consultations."
- [x] FRO & Community org: Creating project, step 2: Project team: "Once you publish your project, others can find it."

### PR DESCRIPTION
**Pull request by greatislander**
Resolves #1069.

 - [x] Admin page for managing estimates and engagements
 - [x] Project admin page for requesting estimates, marking estimates as approved
 - [x] Pagination component
 - [x] Bi-directional notifications

### Prerequisites

If this PR changes PHP code or dependencies:

- [x] I've run `composer format` and fixed any code formatting issues.
- [x] I've run `composer analyze` and addressed any static analysis issues.
- [x] I've run `php artisan test` and ensured that all tests pass.
- [x] I've run `composer localize` to update localization source files and committed any changes.

If this PR changes CSS or JavaScript code or dependencies:

- [x] I've run `npm run lint` and fixed any linting issues.
- [x] I've run `npm run build` and ensured that CSS and JavaScript assets can be compiled.

### CODE REVIEW

**Comment by chosww** [comment]
I found a bug on admin view, when an estimate is requested; I saw the new notification on Admin's dashboard page, and I marked as read. After that, I navigated to "All notifications", and there was 0 unread, but once I click All, I see unread 1, but there's nothing when I clicked unread once again.

**Comment by greatislander** [comment]
> 

Can you pull the branch and check that again? I think that may be resolved in a recent commit.

**Comment by chosww** [comment]
Found another bug when a user with community org role is invited as a connector to an engagement, and they view all notifications page crashes the app on "All" tab. 

Error message:

Cannot assign null to property App\View\Components\Notification\OrganizationalContractorInvited::$invitation of type App\Models\Invitation -- app / View / Components / Notification / OrganizationalContractorInvited.php : 19

**Comment by greatislander** [comment]
> Found another bug when a user with community org role is invited as a connector to an engagement, and they view all notifications page crashes the app on "All" tab.
> 
> Error message:
> 
> Cannot assign null to property App\View\Components\Notification\OrganizationalContractorInvited::$invitation of type App\Models\Invitation -- app / View / Components / Notification / OrganizationalContractorInvited.php : 19

Okay, thanks. I think that is the same error I got when I tried to accept the invitation. I'll check it out.

**Comment by greatislander** [comment]
@chosww The bug related to invitation notifications is fixed. Can you test that again and approve if it's working for you?

**Pull request merged**
